const mainData=[
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    },
    {
        Image:'./images/pig.jpg',
        title:'母猪的产后护理',
        img:'../images/github.jpg',
        span:'叶桑'
    }
]